# Set up Homebrew environment
if [ -x "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x "/usr/local/bin/brew" ]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

# Add homebrew binaries
export PATH="/usr/local/bin:$PATH"

# Add my custom commands
export PATH="$HOME/bin:$PATH"

# Add current bin for easier rails dev
export PATH="./bin:$PATH"

export PATH="$HOME/.npm-packages/bin:$PATH"
